all:
	as -o years.o years.s
	ld -o years years.o
	as -o area2.o area2.s
	ld -o area2 area2.o
	as -o area3.o area3.s
	ld -o area3 area3.o
	as -o area4.o area4.s
	ld -o area4 area4.o
	as -o area5.o area5.s
	ld -o area5 area5.o
clean:
	rm years.o years area2.o area2 area3.o area3 area4.o area4 area5.o area5
