all:
	as -o prog6a.o prog6a.s
	ld -o prog6a prog6a.o
	as -o prog6b.o prog6b.s
	ld -o prog6b prog6b.o
	as -o prog6c.o prog6c.s
	ld -o prog6c prog6c.o
	as -o prog6d.o prog6d.s
	ld -o prog6d prog6d.o
clean:
	rm prog6a.o prog6a prog6b.o prog6b prog6c.o prog6c prog6d.o prog6d
